name: Build, Test, and Deploy to Netlify (Parallel CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: 🧹 Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run lint
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "⚠️ No lint script found, skipping lint step."
          fi  


  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run Tests
        run: |
          if npm run | grep -q "test"; then
            npm test -- --ci --passWithNoTests
          else
            echo "⚠️ No test script found, skipping test step."
          fi

  deploy:
    name: 🚀 Deploy to Netlify
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: |
            GitHub Actions deploy - ${{ github.event.head_commit.message }}
          enable-commit-comment: false
          enable-pull-request-comment: true
          enable-commit-status: true
          production-deploy: ${{ github.event_name == 'push' }}
          alias: ${{ github.head_ref || 'main' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
